import { Converter } from '../dist'

describe('default processors', () => {
  test('upper', () => expect(true).toBe(true))
  test('lower', () => expect(true).toBe(true))
  test('trim', () => expect(true).toBe(true))
  test('join', () => expect(true).toBe(true))
  test('map', () => expect(true).toBe(true))
  test('query', () => expect(true).toBe(true))
  test('convert', () => expect(true).toBe(true))
  test('slugify', () => expect(true).toBe(true))
  test('stringFormat', () => expect(true).toBe(true))
  test('escape', () => expect(true).toBe(true))
  test('titleCase', () => expect(true).toBe(true))
  test('truncate', () => expect(true).toBe(true))
  test('fetch', () => expect(true).toBe(true))
  test('stripTags', () => expect(true).toBe(true))
  test('sort', () => expect(true).toBe(true))
  test('slice', () => expect(true).toBe(true))
  test('dateFormat', () => expect(true).toBe(true))
})
